### ISSUE TITLE
The projects are not the newest format. Have to use VS 2015

### ISSUE THREAD

**Issue by CraigChamberlain** [isaacabraham/get-programming-fsharp#4]
I was unable to open in VScode and there was a missing reference to fsharp.core in VS 2017.  I made a new project in VS 2017 and it was structured quite differently, copied over the actual .fs files and it all executed fine and opened in VS code too.

Is there a way to bulk update these to a newer format?

**Comment by isaacabraham** [comment]
@CraigChamberlain can you try the netcore branch? I've already gone through many of the projects to upgrade it to the newer project SDK :-)

**Comment by CraigChamberlain** [comment]
Great. Didn't think to use another branch.

**Comment by AkosLukacs** [comment]
Oh, I missed that branch too, thanks!
@isaacabraham what about adding a note about the netcore branch in the readme, so it's more visible?
